#!/bin/sh -e

VERSION="$1"

. ./scripts/vars

(cd ./dist \
  && if test -z "$(git config user.name)"; then git config user.name "$GIT_USER_NAME"; fi \
  && if test -z "$(git config user.email)"; then git config user.email "$GIT_USER_EMAIL"; fi \
)

if test "$(./scripts/dist-has-tag "$VERSION")" = "true"; then
  (cd ./dist \
    && git tag -d "$VERSION" \
    && git push --delete origin "$VERSION" \
  )
fi

(cd ./dist \
  && git add . \
  && git commit -m "$VERSION" \
  && git tag -a "$VERSION" -m "$VERSION" \
  && git push --follow-tags -u origin dist \
)
