#!/bin/sh

set -e

VERSION="$1"

if [ -z "$(git config user.name)" ]; then git config user.name "$GIT_USER_NAME"; fi
if [ -z "$(git config user.email)" ]; then git config user.email "$GIT_USER_EMAIL"; fi

if test "$(./scripts/dist-has-tag "$VERSION")" = "true"; then
  git tag -d "$VERSION"
  git push --delete origin "$VERSION"
fi

git add .
git commit -m "$VERSION"
git tag -a "$VERSION" -m "$VERSION"
git push --follow-tags -u origin dist
