#!/bin/sh -e

VERSION="$1"

mkdir -p dist

# ensure dirty git working directory
echo "$(date) Travis: $TRAVIS_BUILD_NUMBER" > dist/build_number
cp .travis.yml dist/

# build and/or copy relevant files into dist/
cp -r bin dist/
sed "s/{PT_VERSION}/$VERSION/" Dockerfile.template > dist/Dockerfile
