#!/bin/sh

SUBJECT_TAG="$1"

if [ ! -d "./dist" ]; then
  echo "./dist has not been cloned yet. Clone it with `./scripts/dist-clone`." >> /dev/stderr
  exit 1;
fi

has_tag="false"
if [ ! -z "$(cd ./dist; git tag -l "$SUBJECT_TAG")" ]; then has_tag="true"; fi

printf "$has_tag"
