#!/bin/sh

VERSION="$1"

mkdir -p dist

# ensure dirty git working directory
echo "$TRAVIS_BUILD_NUMBER" > dist/build_number

# build and/or copy relevant files into dist/
cp .travis.yml dist/
cp -r bin dist/
sed "s/{PT_VERSION}/$VERSION/" Dockerfile.template > dist/Dockerfile
