#!/bin/sh -e

VERSION="$1"

. ./scripts/vars

if test -z "$VERSION"; then
  echo "enter a version number" >> /dev/stderr
  exit 1
fi

./scripts/dist-clone

./scripts/dist-prepare "$VERSION"
./scripts/dist-publish "$VERSION"

rm -rf ./dist
