#!/bin/sh -e

. ./scripts/vars

./scripts/dist-clone

LATEST_VERSION="$(./scripts/source-latest-version)"
if test -z "$LATEST_VERSION"; then
  echo "could not determine latest version" >&2
  exit 1
fi
echo "Latest version of $SOURCE is $LATEST_VERSION"

# don't build in cron job when there's already a build for this version
if (test "$TRAVIS_EVENT_TYPE" = "cron" && test "$(./scripts/dist-has-tag "$LATEST_VERSION")" = "true"); then
  "already up to date with source repo. skipping build."
else
  echo "preparing dist"
  ./scripts/dist-prepare "$LATEST_VERSION"
  echo "publishing dist"
  ./scripts/dist-publish "$LATEST_VERSION"
  echo "publish complete"
fi
